name: Java CI - Build

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test the project
        run: cicd/ci/build.sh
        env:
          CI_SECURE_ENV_VARS: true
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_TOKEN: ${{ github.token }}

  release:
    needs: build
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # install dependencies and run semantic-release
      - run: npm install -g semantic-release @semantic-release/{git,changelog,exec}
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}