name: Java CI - Publish

on: [ push ]
#on:
#  push:
#    tags:
#      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup up GPG Key
        run: |
          echo ${{ secrets.GPG_SECRET_KEYS }} | base64 --decode | gpg --import && echo ${{ secrets.GPG_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust
      - name: Maven Central Repository
        run: cicd/ci/build.sh
        env:
          CI_SECURE_ENV_VARS: true
          PULL_REQUEST: false
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_HOST: ${{ secrets.SONAR_HOST }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_TOKEN: ${{ github.token }}
          GPG_EXECUTABLE: gpg
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}